keys:
  - &admin_bigor age1rv0fzywu3p3nktng4m07ancr65er2ayq6u78906hq5zks5y0wuksgzq5xz
  - &host_grospc age1yumu3wgu7y6m87zk5t7p6u2mg69sd78watftwp2yrjaer0j9lyfsq82540
  - &host_minipc age19538wy6mhnh0fceluhcuuetnjuku8jwmhz7l22505zmd26zm7ahqlhdv78
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin_bigor
          - *host_minipc
          - *host_grospc
