{
  config,
  lib,
  modulesPath,
  ...
}:
{
  # ============================================================================
  # File: systems/x86_64-linux/minipc/hardware-configuration.nix
  # Description: Hardware scan results for "minipc"
  # Author: Bigor (Generated by nixos-generate-config)
  # Date: 2025-12-15
  # Purpose: Defines low-level hardware settings, file systems, and kernel modules.
  #          Do not modify manually unless necessary; usually updated via generation.
  # ============================================================================

  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot and Kernel Modules
  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "thunderbolt"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  # File Systems
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/472e7005-6c44-4af4-a270-d96350e91836";
      fsType = "ext4";
    };

    "/mnt/storage" = {
      device = "/dev/disk/by-uuid/a1ee534d-78d8-42df-be26-9cadae8197cf";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/E12E-89E1";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  # Networking
  # Enables DHCP on all interfaces by default.
  networking.useDHCP = lib.mkDefault true;

  # Architecture & Microcode
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
